### ISSUE TITLE
Value constructors available globally

### ISSUE THREAD

**Issue by sadhu89** [dry-rb/dry-monads#107]
Is there a way I could make the value constructors available globally? A bit like the Kleisli gem

**Comment by waiting-for-dev** [comment]
Not sure if it is a good idea, but you can do something like:

```ruby
require 'dry/monads/maybe'
Object.include(Dry::Monads::Maybe::Mixin)
Some(1)
```

But, for sure, it should not be implemented neither recommended by the library itself.

**Comment by flash-gordon** [comment]
👆

**Comment by sadhu89** [comment]
Cool. Could you guys please give me some pointers about why this is discouraged? Thanks!

**Comment by flash-gordon** [comment]
Nobody said it's discouraged, it's just not a dry-monads' task to pollute global namespaces. In my opinion, this is not needed because any code should be scoped for better portability and easiness of understanding.
