### ISSUE TITLE
Line coverage is too low

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-monads#11]
Please get it to ~100% before releasing. This is way below our standards :)

**Comment by flash-gordon** [comment]
I covered [every single thing](https://github.com/dry-rb/dry-monads/tree/master/spec/unit) and no, that [does not work](https://codeclimate.com/github/dry-rb/dry-monads/coverage/572473ab596e17000100332f) :) I dumped CodeClimate report to a file and it's fine:
```
[2] pry(main)> JSON.load(File.read('/var/folders/kr/sj821pp55tx4s2ylb3zf75yw0000gn/T/codeclimate-test-coverage-0833261b-c0c3-4141-90c0-498c2b6059f2.json'))
=> {"repo_token"=>"foo",
 "source_files"=>
  [{"name"=>"lib/dry/monads.rb",
    "blob_id"=>"fe5b9ace63c2583d42e5101150572a7336259924",
    "coverage"=>"[1,1,1,null,1,1,1,null,1,5,null,null,1,2,null,null,1,4,null,null,1,4,null,null,1,3,null,null,null]",
    "covered_percent"=>100.0,
    "covered_strength"=>1.8,
    "line_counts"=>{"total"=>29, "covered"=>16, "missed"=>0}},
```
^ method definitions are covered actually so I filed a bug to CC.

**Comment by solnic** [comment]
@AMHOL noticed the same issue in dry-container. If it works locally then
let's just ignore CC for now

**Comment by flash-gordon** [comment]
Special thanks go to @timriley for https://github.com/dry-rb/dry-monads/commit/f8b30a289fc050d1fcc904969d04db742c202448 :)
@AMHOL you can take a look at the commit. I guess it can resolve container's issue as well.
