### ISSUE TITLE
Spring (Rails pre-loader) and dry-monads are incompatible

### ISSUE THREAD

**Issue by johnmaxwell** [dry-rb/dry-monads#115]
Thank you for your work on the dry project. 

I wanted to make you aware of this incompatibility with spring. Even though I'm opening this ticket on your project first, I intend to open a ticket with spring as well.

**Describe the bug**

Spring (Rails pre-loader) and dry-monads are incompatible. Spring replaces Kernel#raise with a version that sanitizes backtrace. dry-monads raises an instance of Halt with a frozen EMPTY_ARRAY. An error is generated when Failure(..) is used an a dry-monads Do implementation.

Spring is a installed by default on `rails new`

**To Reproduce**

https://github.com/johnmaxwell/spring_dry_monads_break

```ruby
require 'dry/monads/do'

class BreakHalt
  include Dry::Monads[:result]
  include Dry::Monads::Do.for(:call)

  def call()
    yield break_halt
  end

  def break_halt
    Failure('anything')
  end
end

BreakHalt.new.call
```

Results in an error like:

    .../lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:305:in `reject!': can't modify frozen Array (FrozenError)

**Expected behavior**

Returns Failure instance

**Your environment**

- Affects my production application: NO
- Ruby version: 2.6.5
- OS: Mac
- Rails: 6.0.1
- Spring: 2.1.0
- dry-monads: 1.3.2

**Comment by flash-gordon** [comment]
Thanks for letting me know and for all the work to narrow it down. I'm pretty sure it's a bug in rails. I don't patch ruby neither do I use dirty hacks, only Ruby. I can change `EMPTY_ARRAY` to `[]`, not a big deal though. We'll see what they say :)

**Comment by flash-gordon** [comment]
Pushed 1.3.3
