### ISSUE TITLE
Support `#<=>` over Maybe

### ISSUE THREAD

**Issue by endgame** [dry-rb/dry-monads#126]
Currently, `<=>` over `Maybe` values returns `0` if both sides are `None`, and `nil` otherwise. We could lift `<=>` over `Maybe`.

## Examples

```ruby
None <=> Some(2)
=> -1

Some(3) <=> None
=> 1

None <=> None
=> 0

# Calls <=> on the contents of each Some
Some(3) <=> Some(4)
=> -1
```

**Comment by flash-gordon** [comment]
This comes from `Kernel`
```
 :001 > method(:<=>)
 => #<Method: Object(Kernel)#<=>(_)>
```
I don't see how implementing `<=>` would be useful tbh, beyond some "clever" tricks.

**Comment by endgame** [comment]
As one example, I've been using sorbet `T::Struct`s along with a helper that implements `<=>` on structs by calling `<=>` on elements in order. Structs that contain `Maybe` values currently do not compare properly, which limits the utility of putting a `Maybe` inside a `T::Struct` if you ever need to compare structs.

**Comment by flash-gordon** [comment]
One can implement `<=>` via a monkey-patch or an extension.
