### ISSUE TITLE
`include Dry::Monads[:do]` removes private method protection on instance methods

### ISSUE THREAD

**Issue by anicholson** [dry-rb/dry-monads#128]
**Describe the bug**

Adding `include Dry::Monads[:do]` to a class silently removes `private` (or indeed any) visibility modifiers from all methods.

**To Reproduce**

1. run `ruby minimal_case.rb` from [this gist][0] (sorry, GH wouldn't let me attach the file directly)

**Expected behaviour**

Expected: raises `NoMethodError (private method 'reveal' called for #<WithSecret:0xdeadbeef>`
Actual: outputs `Oops, I swore I wouldn't tell!` to STDOUT

**Your environment**

- Affects my production application: NO
- Ruby version: 2.6.6, 2.5.1
- OS: Linux

**Notes**

* We notice that [`wrap_method`][1] doesn't accept a protection modifier, so all redefined methods become public by default.
* `Do::All` uses `Module::instance_methods` to determine what to wrap - but ([since at least Ruby 2.0][2]) `Module` also provides `public_instance_methods`, `protected_instance_methods`, and `private_instance_methods`. Could these be used to give the wrapper methods the same visibility as the methods they wrap?
* Given how `private`/`protected`/`public` operate, it might be tricky to do this without accidentally setting the default visibility within the class to a surprising value. I haven't tested this, though.

[0]: https://gist.github.com/anicholson/b578c04866a23069a41fc7fd45d8dad7
[1]: https://github.com/dry-rb/dry-monads/blob/master/lib/dry/monads/do.rb#L108-L118
[2]: https://ruby-doc.org/core-2.0.0/Module.html#method-i-private_instance_methods

**Comment by anicholson** [comment]
It may not be easy to fix this simply. In which case, perhaps a cautionary note in the docs for `Do` might be worthwhile?

**Comment by flash-gordon** [comment]
fixed via #136
