### ISSUE TITLE
`include Dry::Monads[:do]` doesn't work on class methods

### ISSUE THREAD

**Issue by philipce** [dry-rb/dry-monads#132]
It appears the syntax `include Dry::Monads[:do]` doesn't work on class methods.

For example:

```ruby
class MyTest
  class << self
    include Dry::Monads[:try, :result, :do]

    def foo(x)
      a = yield bar(x)
    end

    def bar(x)
      Try { 10 / x }.to_result
    end
  end
end
```
```
irb(main):066:0> MyTest.foo(0)
Traceback (most recent call last):
  2: from (irb):66
  1: from app/persistence/my_test.rb:45:in `foo'
LocalJumpError (no block given (yield))
```
The `include Dry::Monads[:try, :result, :do]` works as expected if not implemented as class methods.

Also, this syntax works fine on class methods:
```ruby
class MyTest
  class << self
    include Dry::Monads[:try, :result]
    include Dry::Monads::Do.for(:foo)

    def foo(x)
      a = yield bar(x)
    end

    def bar(x)
      Try { 10 / x }.to_result
    end
  end
end
```
```
irb(main):059:0> MyTest.foo(0)
=> Failure(#<ZeroDivisionError: divided by 0>)
```

I looked through the issues briefly. Issue https://github.com/dry-rb/dry-monads/issues/92 addressed difficulty getting do-notation working with class methods, but only used the `Do.for(:foo)` syntax. Also https://github.com/dry-rb/dry-monads/issues/68 is a different issue, but I noted the syntax to `include Dry::Monads::Do::All`; I tried it and ran into the same `LocalJumpError`.

**My environment**

- Affects my production application: **NO**
- Ruby version: 2.7.1
- OS: macOS 10.15.5
- dry-monads: 1.3.5

**Comment by esparta** [comment]
[Per do-notation documentation (down in the bottom)][do-notation], you can use `Dry::Monads[:do]` with class method using extend:

```ruby
class Test 
  extend Dry::Monads[:try, :result, :do]
  class << self
    def foo(x)
      a = yield bar(x)
    end
    def bar(x)
      Try {  10 / x }.to_result
    end
end

Test.foo(0)
# => Failure(#<ZeroDivisionError: divided by 0>)
```
Note also the extend is called before the class-method definitions.

[do-notation]: https://dry-rb.org/gems/dry-monads/1.3/do-notation/

**Comment by philipce** [comment]
Whoops, I missed that in the docs. That'll work great for me. Thanks!

**Comment by esparta** [comment]
No problem, glad to help.
