### ISSUE TITLE
Pattern Matching is broken for Array

### ISSUE THREAD

**Issue by ndan** [dry-rb/dry-monads#141]
#### Describe the bug

Pattern matching doesn't work for `Success([1]) in Success([a])`, hoverer it works for `Success[1] in Success[a]`

#### To Reproduce

```
[1] pry(main)> Success([1]) in Success([a])
NoMatchingPatternError: Success([1])
from (pry):41:in `<main>'

# The working examples:
[2] pry(main)> Success[1] in Success[a]
=> nil
[3] pry(main)> Success([1]) in Success[a]
=> nil
```

#### Expected behavior

`Success([a])` should work exactly the same as `Success[a]`, otherwise [examples](https://dry-rb.org/gems/dry-monads/1.3/pattern-matching/) should be updated.

#### My environment

- Affects my production application: No, since there is a workaround (eg `Success[1]`)
- Ruby version: ruby 2.7.2p137
- OS: MacOS Big Sur

**Comment by flash-gordon** [comment]
Could you point which example should be updated?

**Comment by ndan** [comment]
Here
<img width="921" alt="Screenshot 2021-02-15 at 16 26 01" src="https://user-images.githubusercontent.com/760394/107922389-e8746e00-6faa-11eb-969b-217ee69edda2.png">

**Comment by flash-gordon** [comment]
Thank you! I'll look into that but I think the current behavior is intentional. I know the API is confusing in this part but there were reasons why it happened. Constructing values with `Success.[]/Failure.[]` came earlier than PM, then everything messed up. I'll try to improve things in 2.0 since it has to be a breaking change.

**Comment by andhapp** [comment]
@flash-gordon Hey, is it possible to update the documentation in the mean time. Had me totally stumped today. :-)
