### ISSUE TITLE
[Feature request] Map Some(nil) to None automatically

### ISSUE THREAD

**Issue by gogainda** [dry-rb/dry-monads#15]
In scala it is possible to have Some of null value, which could lead to npe. I see that right now we rise an exception. Maybe we could convert Some(nil) to None automatically?

**Comment by flash-gordon** [comment]
Hello, @gogainda 

I don't think this is a good idea because there is `#Maybe` for cases when you expect nil as an input.
```ruby
[2] pry(main)> require 'dry/monads'
=> false
[3] pry(main)> include Dry::Monads::Maybe::Mixin
=> Object
[4] pry(main)> Maybe(1)
=> Some(1)
[5] pry(main)> Maybe(nil)
=> None
[6] pry(main)>
```
It's better to fail ASAP if you don't expect nil so we can't have this npe issue.

**Comment by gogainda** [comment]
interesting, thanks

**Comment by flash-gordon** [comment]
So is it OK, can I close the issue? :)

**Comment by gogainda** [comment]
sure
