### ISSUE TITLE
Task#then alias for #bind conflicts with Kernel#then

### ISSUE THREAD

**Issue by cllns** [dry-rb/dry-monads#162]
`Dry::Monads::Task` has an alias for [its `bind` method as `then`](https://github.com/dry-rb/dry-monads/blob/35d742fe872372a644eb7a3cf9d875736874b3e2/lib/dry/monads/task.rb#L129).

Ruby 2.6 itself [added `Kernel#then` as an alias to `Kernel#yield_self`](https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/) (first note) ~11 months after `dry-monads` added its alias.

`dry-monads`'s `then` takes precedence, but conflicting with `Kernel` methods is something we generally avoid.

Since it's just a helpful alias, and `bind` is already used a lot in `dry-monads`, I think it could be OK to just remove this alias, though that's technically a breaking change (or could wait for a 2.0 release, since this is pretty low stakes.)

**Comment by flash-gordon** [comment]
I think we can add a deprecation warning and cut a release. I would like to push 2.0 sometime soon anyway. `.then` is a common name for chaning promises/futures/etc but I agree we shouldn't shadow `Kernel` here.

**Comment by cllns** [comment]
In Elm this is called [`andThen`](https://package.elm-lang.org/packages/elm/core/latest/Task#andThen) (it's also what they call it for `Result` and `Maybe` too), so `and_then` could be another option. 

But, might be simpler to just stick to `bind` especially since `and_then` and `then` are quite different.

**Comment by hi-tech-jazz** [comment]
I really like the concept of `and_then` and `or_else` used in the Upgrow project. For example, then you could do:
```
operation.call(input)
.and_then do |value|
# handle success
end
.or_else do |errors|
# handle failure
end
```

https://github.com/szTheory/upgrow/blob/main/lib/upgrow/result.rb

Could that be interesting in this project?
