### ISSUE TITLE
bind_err (or a way to execute code on None or Left)

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [dry-rb/dry-monads#31]
Might seem stupid, but based on all Monads, there is no way for me to execute code on a None or a Left.

My usecase is for example in a service object returning a monad in a controller:

I want to 

```ruby
result.bind do |value|
  render json: value.as_json
end.bind_err do |err|
  render_error err
end
```

Unfortunately, can't do it without checking the type.
In addition a simple way to identify if an object is a monad will be extremely helpful: allows interacting with "legacy code" more easily, and wrap the object in a monad if it's not wrapped already.

**Comment by timriley** [comment]
Would `#or` do what you need? https://github.com/dry-rb/dry-monads/blob/747bdfe2e07754daa6581546720f4db8baabfb0a/lib/dry/monads/either.rb#L97-L113

**Comment by Fire-Dragon-DoL** [comment]
@timriley it would, but it feels really weird passing an argument for_not_ using it

**Comment by timriley** [comment]
Sorry, what do you mean exactly about passing an argument? Mind sharing an example, perhaps?

**Comment by Fire-Dragon-DoL** [comment]
Sorry @timriley , looks like you are right, for some reason I thought the only usage was `Left(123).or(Left(456))`. My example is:

```ruby
def complex_operation_which_fails
  Left(:unauthorized)
end

class WhateverController
  def create
    complex_operation_which_fails.bind do |value|
      render json: value.as_json
    end.or do |error_code|
      head error_code
    end
  end
end
```

I'll close the issue

**Comment by rewritten** [comment]
You should use a result matcher here, otherwise you will end up calling `.or` on the return value of `render` which is not a monad. You can also wrap `render :json` in a Right, but it would sound really artificial.

**Comment by Fire-Dragon-DoL** [comment]
@rewritten Mh.... it's extremely verbose for a return value I don't even care about, I might need to build a utility method for that. Thanks for the direction, I'll check from there.

**Comment by timriley** [comment]
Thanks for suggesting that approach, @rewritten – it's a good idea in this case. It's also what we had in mind when building [dry-matcher](http://dry-rb.org/gems/dry-matcher/)! @Fire-Dragon-DoL, this might do exactly what you need here. We have an [either matcher](http://dry-rb.org/gems/dry-matcher/either-matcher/) that works out of the box. It'd let you do something like this:

```ruby
Dry::Matcher::EitherMatcher.(value) do |m|
  m.success do |value|
    render json: value.as_json
  end

  m.failure do |error_code|
    head error_code
  end
end
```

**Comment by Fire-Dragon-DoL** [comment]
Thanks, yes I ended up writing my own matcher (didn't notice there was an EitherMatcher...DOH!).

Works perfectly!
