### ISSUE TITLE
Why there is no .ap method?

### ISSUE THREAD

**Issue by v-shmyhlo** [dry-rb/dry-monads#32]
Hello everybody. Was playing with dry-monads recently and was very surprised by the fact that there is no .ap method, i know i can implement it using .bind but still it is very convenient method, why it is not in the library by default?

**Comment by flash-gordon** [comment]
Hi there. This is the same old story about adding foreign methods to lib's classes. I personally don't like the approach when you have to add some methods in order to make gems work together, *but* I'm OK with adding it as an opt-in extension, like [this one](https://github.com/dry-rb/dry-monads/blob/master/lib/json/add/dry/monads/maybe.rb)

**Comment by v-shmyhlo** [comment]
Sorry, can you please explain me why .ap method is considered foreign? I mean its part of the Applicative interface and as far as i know Monad implements Applicative. The main reason why i asked about this is that i think it is much more convenient to write:
```ruby
f = -> (x, y) { x + y }.curry
Some(f).ap(Some(1)).ap(Some(2))
```
instead of:
```ruby
f = -> (x, y) { x + y }.curry
Some(f).chain { |f| Some(1).fmap(f) }.chain { |f| Some(2).fmap(f) }
```
Also i don't want to monkeypatch dry-monad classes in order to get what i want as i think it is poor practice.
Also i know dry-monads is inspired by kleisli gem and it has this functionality:
https://github.com/txus/kleisli#-applicative-functors-apply

**Comment by flash-gordon** [comment]
Ah, sorry, I got you now. The main reason of course is that Ruby doesn't have a nice support for lambdas/functions, so it's not a very practical feature in my opinion. Do you have any real-world-like example for this?

**Comment by v-shmyhlo** [comment]
Well i basically follow convention to define classes with #call method which used kinda like functions (receive input, return output), and i know dry-rb uses same convention for some things (dry-transaction, dry-validation, dry-logic, dry-matcher), so i think there is a lot of places where we use objects as functions and #ap method fits very naturally in such environment.
As an example:
```ruby
config = load_config # returns Either 
argument = get_controller_params # returns Either
result = config.map { |x| MyServiceObject.new(x) }.ap(argument)
```

**Comment by flash-gordon** [comment]
Very good point. We didn't wrap callable objects with monads, at least not yet, but this makes sense. This will introduce an unnecessary overhead in dry-* libs in my opinion, but for application code this shouldn't be a problem in most of the cases. I'm going to add support for this and give it a try in my applications, thanks.

**Comment by v-shmyhlo** [comment]
Awesome! thank you :+1:

**Comment by niksosf** [comment]
Thanks for implementing the applicative. Just wanted to add to the knowledge base of thread in case someone googles it; the applicative allows for parallelism that the nested version does not. Just as @v-shmyhlo 's example. At least in the case of of the Task monad elsewhere, where you can send off computations necessary to generate the to-be arguments for the function. `Task(f).ap(Task(arg1)).ap(Task(arg2))`

**Comment by flash-gordon** [comment]
@niksosf good point. Btw, I’m planning to add the `Task` monad in future
