### ISSUE TITLE
Should `or` return a instance of the given Monad?

### ISSUE THREAD

**Issue by scepticulous** [dry-rb/dry-monads#34]
I am wondering if it would be better if ``or`` would return ``Some`` or ``Right`` instead of the result of the given block.  Are there any arguments against it, because right now the developer has to make sure, that the result includes conversion to the given type.
However I am aware that this assumes that the block result is always treated as success.

**Comment by flash-gordon** [comment]
The main issue here is backward compatibility. dry-monads was extracted from kleisli gem which follows this convention, and kleisli in order just copied the type of `Monad#bind`. We can have something like `#or_fmap` as a twin of `#fmap`, wdyt?

**Comment by scepticulous** [comment]
I agree with your arguments. ``or_fmap`` sounds good. One more alternative would be ``map_error``. There are similar functions implemented in Elm.

**Comment by flash-gordon** [comment]
@scepticulous I pushed this to master, sorry it took so long, was pretty busy with ROM stuff during this period. I'm going add some more features and release 0.3 version in a week or so.

**Comment by scepticulous** [comment]
Great news. Thanks a lot.
