### ISSUE TITLE
monads transforms dry-structs into hash

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-monads#38]
After update to `dry-monads` 0.3.0 monads convert `dry-struct` to hashes:

```ruby
class A < Dry::Struct
  attribute :name, Types::Strict::String
end

m = M.Maybe(A[name: '123'])
# => Some(#<PersistCustomerCommand::A name="123">)
m.bind { |a| a.inspect }
=> "{:name=>\"123\"}"
```

**Comment by flash-gordon** [comment]
That happened because structs implement `to_hash` interface. I will work around this, but is it _right_, @solnic? I also want to note that this caveat affects only `to_hash` and `to_ary` (that I used for `List` recently) should be fine.
