### ISSUE TITLE
M.Maybe should response to `success?`/`failure?`

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-monads#40]
To remove a difference between M.Maybe and Right/Left monads, and to maintain better polymorphism, `M.Maybe` monad should respond to `#success?` and `#failure?` methods

**Comment by scepticulous** [comment]
@Kukunin I think that is a great idea. So I would like it as well.

**Comment by nicosuave** [comment]
I concur. Would be nice to match on the `Try` monad

**Comment by zacheryph** [comment]
I know this has been in place for 5 years and I have only been using dry-rb for a year.

Though, I am confused as to why `None()` would ever be considered a failure?

**Comment by flash-gordon** [comment]
Only for duck-typing I guess, I prefer `.none?`

**Comment by zacheryph** [comment]
In that regard, shouldn't Result respond to `none?` and `some?`

**Comment by flash-gordon** [comment]
You can .to_maybe + .none?
