### ISSUE TITLE
List#map could return Enumerator

### ISSUE THREAD

**Issue by scepticulous** [dry-rb/dry-monads#41]
Currently [List#map](https://github.com/dry-rb/dry-monads/blob/master/lib/dry/monads/list.rb#L95) raises an error if no block is given. However this makes it impossible to do something like `map.with_index` as it is possible with all regular ruby Enumerables. I would really like to have this normal behaviour for List#map as well.
Could this be done and are there any cons to it, that I am not aware of?

**Comment by flash-gordon** [comment]
No specific reason I reckon, only lack of time :) I'll get back to monads in a few weeks and address it, thanks for reporting
