### ISSUE TITLE
Destructuring of RightBiased value is inconsistent and ends up breaking Hash values and arguments

### ISSUE THREAD

**Issue by saverio-kantox** [dry-rb/dry-monads#51]
Using different forms of binding, the destructuring has different way of breaking.

Set up:
```ruby
class Data < Hash
  # This is the data that's passed around. Has method access and different to_s for the sake of testing
  def method_missing(name, *args)
    return fetch(name) if key?(name) && args.empty?
    super
  end

  def to_s
    "<Data #{super}>"
  end
end

add_wheel = ->(car, wheel) { car.wheels << wheel; car }
```

Break 1: `wrong number of arguments (1 for 2)`
The proc receives a single plain hash `{color: 'red', wheels: [], radius: 36}`
```ruby
Right(Data[color: 'red', wheels: []])
  .bind(Data[radius: 36], &add_wheel)
```

Break 2: The second argument is converted to plain hash:
```ruby
Right(Data[color: 'red', wheels: []])
  .bind(add_wheel, Data[radius: 36])
# => <Data {:color=>"red", :wheels=>[{:radius=>36}]}>
```
It should have been `<Data {:color=>"red", :wheels=>[<Data {:radius=>36}>]}>`

Break 3 (related to break 2): `undefined method 'radius' for {:radius=>36}:Hash`
```ruby
add_big_wheel = ->(car, wheel) { car.wheels << wheel if wheel.radius > 35; car }

Right(Data[color: 'red', wheels: []])
  .bind(add_big_wheel, Data[radius: 36])
```

(The same happens with `Result` instead of `Right` of course, the examples are with version 0.3.1)

**Comment by flash-gordon** [comment]
@saverio-kantox this happens due to your class implements `to_hash` which is used by ruby for collecting keyword arguments with `**`. Instead of subclassing built-in classes, I would recommend implementing a proxy that does not have `to_hash` neither via `method_missing` nor `respond_to?`

**Comment by saverio-kantox** [comment]
:( I'm using Hashie's `Dash` everywhere... I guess that you will tell me to use Dry::Struct instead, and with good reasons, but Structs are slightly too type-strict for what I need, while dashes are just right.

**Comment by saverio-kantox** [comment]
Another example that makes this problem apparent, much more than the others:
```ruby
Right(data: {a: :foo}).bind(data: {b: :bar}) { |*args| puts args.inspect }
# => [{:data=>{:a=>:foo}}]
```
as you see, the argument to the `bind` call may be discarded depending on the value inside the Either.

I just wonder why destructuring is there at all, and if it could be removed. I see no feature depending on it.

**Comment by flash-gordon** [comment]
This is intended, inputs are merged, not replaced (with `.merge`). Here's an example:
```ruby
data = Success(email: 'foo@bar.com')
data.bind(name: 'John') { |user| user_repo.create(user) }
```
It's useful when you pass several distinct keywords along a chain of operations.

```ruby
def create_user(user_info:, **rest)
  user = user_repo.create(user_info)

  Success(user: user, **rest)
end
```

**Comment by flash-gordon** [comment]
And I wouldn't recommend use dry-struct for this. Roll out your own custom proxy, it's like 10 lines of code.
