### ISSUE TITLE
setup new gem services

### ISSUE THREAD

**Issue by ttdonovan** [dry-rb/dry-monads#6]
Now that the `proposal` branch has been merged into `master`. Could someone with the correct credentials please setup services for Travis CI and CodeClimate. Thanks!

**Comment by flash-gordon** [comment]
@timriley I added CodeClimate but travis requires admin access. Can you help with this?

**Comment by solnic** [comment]
@flash-gordon done

**Comment by flash-gordon** [comment]
@solnic ❤️

**Comment by flash-gordon** [comment]
@solnic @ttdonovan I would be great to add test coverage as well. Codeclimate requires admin access for this: settings -> test coverage -> at the bottom of the page choose travis.

**Comment by timriley** [comment]
Taking care of this now.

**Comment by timriley** [comment]
oh, @AMHOL did it 4 minutes ago! 💯

**Comment by AMHOL** [comment]
Yeah but I did it wrong

**Comment by AMHOL** [comment]
OK, should be fixed now
