### ISSUE TITLE
undefined Right after upgrading to 1.0.0

### ISSUE THREAD

**Issue by vanitu** [dry-rb/dry-monads#62]
Hi.
After upgrading Dry-Transaction and Dry-Monads we face a big issue with breaking changes.

Currently in each transaction we fail with:
`NoMethodError: undefined method Right for.....`

As I understand this happen due to replacing Right/Left with Success/Failure, but this change was stated as backward compatible. 

However the worst part is that we use method 'value' on Right/Left instance to retrieve transaction results. But currently Success  class no longer has method **value** which was replaced with **value!**

Can you help to understand do you plan to support backward compatibility and help to rectify such cases and share what are correct usage of DryTransaction to avoid such cases in future?

Honestly these breaking changes force to rework all parts where DryMonads were ever used and cancel almost all benefits of continue using Dry as risk of having similar troubles in future

**Our Success(Right) context is:**
dry-monads (0.4.0)
      dry-core (~> 0.3, >= 0.3.3)
      dry-equalizer
dry-transaction (0.13.0)
      dry-container (>= 0.2.8)
      dry-events (>= 0.1.0)
      dry-matcher (>= 0.7.0)
      dry-monads (>= 0.4.0)

**Our Failure(Left) context is:**
dry-monads (1.0.0)
      dry-core (~> 0.4, >= 0.4.4)
      dry-equalizer
dry-transaction (0.13.0)
      dry-container (>= 0.2.8)
      dry-events (>= 0.1.0)
      dry-matcher (>= 0.7.0)
      dry-monads (>= 0.4.0)

**Comment by flash-gordon** [comment]
@vanitu `#value` was deprecated in 0.4.0 and dropped in 1.0.0, this was properly reflected in the [changelog](https://github.com/dry-rb/dry-monads/blob/master/CHANGELOG.md#breaking-changes).

**Comment by vanitu** [comment]
@flash-gordon  Yes. I see that in change log. but did you plan to add any Depreciation warning? as I never see that warning while using 0.4.0.

**Comment by flash-gordon** [comment]
@vanitu that's odd, it should be there https://github.com/dry-rb/dry-monads/commit/a22490eaf6894ff7dd3dd3d546c2659f18de43f5#diff-e111bc52d861028b1f0c455ec3d02140R22
I saw it in my project so I can't say you don't see it :( 
Perhaps, something is not right with the dry-core's deprecation module, it should log to stdout by default.

**Comment by flash-gordon** [comment]
btw, WRT breaking changes, dry-rb gems follow [semver](https://semver.org/) and most of them are didn't reach 1.0 yet.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

If you're not OK with this, you probably should not use them because things may and will break.  Nevertheless, we're trying to provide a smooth upgrade path whenever we can. You just need to pay attention to changelogs before upgrading your deps.

I'm closing this issue since I don't think here's a problem in dry-monads, feel free to ask questions here or on the gitter channel, though.

**Comment by vanitu** [comment]
@flash-gordon 

I've checked now on 0.4.0 and no Depreciation warning.

```{ruby}
include Dry::Monads
 => Object
Right(1)
 => Success(1)
Right(1).value
 => 1
Right(1).value!
 => 1
Left(2)
 => Failure(2)
Left(2).value!
Dry::Monads::UnwrapError: value! was called on Failure(2)
	from (irb):34
Left(2).value
 => 2
```

Also I can't get Version  using (don't know if this expected behaviour), while it is exists in version.rb
```{ruby}
2.4.2 :037 > Dry::Monads::VERSION
NameError: uninitialized constant Dry::Monads::VERSION`
```

**Comment by flash-gordon** [comment]
@vanitu thanks for reporting, that's a bug in dry-core actually, I'll fix today

**Comment by flash-gordon** [comment]
@vanitu you should be able to update dry-core to 0.4.7 which shows deprecations correctly. As an alternative, you can run `Dry::Core::Deprecations.set_logger!` at startup without updating, this will have the same effect.

**Comment by flash-gordon** [comment]
Technically, neither of them is correct. `Success` and `Failure` wrap values of different types, that's the whole point of the Result type. If you're sure the values inside them have the same type then the idiomatic way is
```ruby
result.value_or { result.failure }
```

Also, there is dry-matcher

**Comment by vanitu** [comment]
Thanks. I think my code was misleading. 
I wrote just for less characters ) without any context.

Properly it should work as  (hope this is correct way )

```{ruby}

if result.success?
  #do smith with result.success 
else
  # process fail using result.failure
end

```
