### ISSUE TITLE
v1.1.0 NameError: uninitialized constant Dry::Monads::List

### ISSUE THREAD

**Issue by niksosf** [dry-rb/dry-monads#73]
Hi there I have rails 5.1.2 with dry-monads 1.1.0 in Gemlock, an upgrade from 0.4.0. I am not getting errors such as 

`NameError: uninitialized constant Dry::Monads::List`

and when calling `Dry::Monads.Right(1)` it throws:

`NoMethodError: private method `Right' called for Dry::Monads:Module`

What might I be missing?

**Comment by flash-gordon** [comment]
Reading [changelogs](https://github.com/dry-rb/dry-monads/blob/master/CHANGELOG.md)? :)

tldr;
```ruby
require 'dry/monads/list'
# Dry::Monads.Succees instead of Dry::Monads.Right
```

**Comment by niksosf** [comment]
@flash-gordon ha my mistake. was just writing to call false alarm. But on a unrelated note, do you accept/are you planning on updating the documentation about List monoid having an #apply method?

**Comment by flash-gordon** [comment]
Feel free to send a PR. We do have docs for API, though. https://www.rubydoc.info/gems/dry-monads/Dry/Monads/List However, `List#apply` there lacks examples.

**Comment by niksosf** [comment]
Cool, will submit a PR soon thanks!
