### ISSUE TITLE
Suggestion: `List#traverse` should be `List#sequence`

### ISSUE THREAD

**Issue by bjarkevad** [dry-rb/dry-monads#85]
Coming from Haskell and Scala, the naming of `List#traverse` threw me off.

The Haskell signatures of both functions for reference:
`sequence :: (Traversable t, Monad m) => t (m a) -> m (t a)`
`traverse :: (Traverseable t, Applicative f) => (a -> f b) -> t a -> f (t b)`

**Comment by flash-gordon** [comment]
`List#traverse` accepts a block, its block-less behavior equivalent to `List#sequence` for convenience.
