### ISSUE TITLE
Docs for `Try#fmap` and `Try#bind` are flipped

### ISSUE THREAD

**Issue by bjarkevad** [dry-rb/dry-monads#86]
https://dry-rb.org/gems/dry-monads/try/#bind describes `fmap`, e.g. mapping with a pure function.
https://dry-rb.org/gems/dry-monads/try/#fmap describes chaining `Try`s.

**Comment by flash-gordon** [comment]
Yeah, it should be improved. I'm not sure why it's written like this.

**Comment by tmikeschu** [comment]
Hello! Could I pick up this issue?

**Comment by flash-gordon** [comment]
@tmikeschu sure! Docs are in https://github.com/dry-rb/dry-rb.org

**Comment by tmikeschu** [comment]
Thanks @flash-gordon ! https://github.com/dry-rb/dry-rb.org/pull/305

**Comment by flash-gordon** [comment]
thanks, it's merged!
