### ISSUE TITLE
[Feature Request] Extract bind from Do notation

### ISSUE THREAD

**Issue by jamiehodge** [dry-rb/dry-monads#88]
It would be very nice if `Do.bind` was available without the `yield` overload. Please extract https://github.com/dry-rb/dry-monads/blob/master/lib/dry/monads/do.rb#L129-L134. Ideally, there would also be a mixin that would allow for:

```ruby
bar = bind foo
qux = bind baz(bar)
...
```

**Comment by jamiehodge** [comment]
This change would have the added benefit of not having to reach for the `All` mixin to use the same behaviour in private methods.

**Comment by jamiehodge** [comment]
@flash-gordon do you have the time to work on this?

**Comment by flash-gordon** [comment]
@jamiehodge I will do but atm I have other things to work on

**Comment by flash-gordon** [comment]
resolved by #95
