### ISSUE TITLE
Implementing my own monad?

### ISSUE THREAD

**Issue by spavikevik** [dry-rb/dry-monads#91]
Hey there, thanks for the great work!

Although I've noticed you've been working on dry-effects for algebraic effects (and it might probably be the best solution for my problem), I was wondering what path should I take if I wanted to implement my own monads (logging monad and retry monad would be my top priority for my use case right now).

And btw, is there any roadmap on dry-effects?

**Comment by flash-gordon** [comment]
Hi there. Monads of dry-monads rely on the interface, as in, `fmap`/`bind`/`pure`, just as they should.  You can create your own monad, there's nothing special about it, really, but I don't think dry-monads itself could/should provide any framework for this. Speaking of effects, my plan is to gradually implement a bunch of effects in a manner similar to dry-monads. I will think about extension points along the way but writing a custom effect shouldn't be hard anyway. I already have a working prototype in production which I have been using for a few months, quite successfully. My immediate goal is to replace my homegrown solution with a library.

Sorry for this late response, please use our forum for this kind of questions, we use GH for bug tracking and approved feature requests, see [CONTRIBUTING.md](https://github.com/dry-rb/dry-monads/blob/master/CONTRIBUTING.md).
