### ISSUE TITLE
Do-notation with class methods

### ISSUE THREAD

**Issue by tyrcho** [dry-rb/dry-monads#92]
Is there any way to use the do notation when the method is a class method rather than an instance method ?

We are struggling to find an appropriate syntax, and are reluctant to change our existing codebase which does not always instanciate classes ...

**Comment by tyrcho** [comment]
I've got an answer on the chat, here is a complete working example in case you want to update the doc ... 


```ruby
require 'dry/monads/result'
require 'dry/monads/do'

class CreateAccount

  class << self
    include Dry::Monads::Result::Mixin
    include Dry::Monads::Do.for(:call)
  end

  def self.call(params)
    values = yield validate(params)
    account = yield create_account(values)
    owner = yield create_owner(account, values)

    Success([account, owner])
  end

  def self.validate(a)
    Success(a)
  end

  def self.create_account(a)
    Success(a + 1)
  end

  def self.create_owner(a, b)
    Success([a, b])
  end
end

CreateAccount.call(1)
```

**Comment by davydovanton** [comment]
@tyrcho hey, thanks for investigation. Do you want to update documentation for this?

**Comment by tyrcho** [comment]
Well, I think https://github.com/dry-rb/dry-rb.org/blob/master/source/gems/dry-monads/1.0/do-notation.html.md should be updated. I'm not a seasoned rubyist but my colleague is and he could not guess the syntax either.
