### ISSUE TITLE
Map monoid

### ISSUE THREAD

**Issue by niksosf** [dry-rb/dry-monads#99]
Hi there, I was curious whether you'd be interested in implementing the Map monoid in Dry-Monad, an inspiration for this is https://github.com/DrBoolean/immutable-ext . I was thinking in the line of 

```
name_map = Map(
 {
   first: Some("Joe"), 
   last: None(),
}
)

# Hash -> String
SayHi = -> (name_hash) {
  name_hash[:first] + name_hash[:last] + ', hi' }

name.bind{|name_hash| Dry::Monads.Maybe(SayHi(name_hash) } # => name_map, because there's a None(); had last name existed, it would be Some("Joe Smith, hi")

```

Perhaps you could use a hand in implementing this?

**Comment by flash-gordon** [comment]
Thanks for the suggestion, it'll be in the next version: https://github.com/dry-rb/dry-monads/pull/103 I'll push it later this week.
